from __future__ import annotations

import argparse
from pathlib import Path


def main(pdf_path: str = "data/sample_layout.pdf") -> None:
    from app.ingest.pipeline import ingest_pdf

    path = Path(pdf_path)
    if not path.exists():
        raise SystemExit(f"PDF not found: {path}. Pass an existing PDF path.")

    out = ingest_pdf(path)
    print("MODE:", out["probe"]["probe_detected_mode"])
    print("PAGES:", len(out["pages"]))
    print("BLOCKS:", len(out["blocks"]))
    print("CHUNKS:", len(out["chunks"]))

    if out["blocks"]:
        b = out["blocks"][0]
        print("\nFIRST BLOCK")
        print("id:", b.block_id)
        print("type:", b.block_type)
        print("page:", b.page_index)
        print("heading_path:", b.heading_path)
        print("text:", b.text[:200])

    if out["chunks"]:
        c = out["chunks"][0]
        print("\nFIRST CHUNK")
        print("id:", c.chunk_id)
        print("pages:", c.page_indices)
        print("heading_path:", c.heading_path)
        print("block_types:", c.block_types)
        print("text:", c.text[:300])


def test_ingest_pipeline_smoke(tmp_path: Path, monkeypatch) -> None:
    from app.ingest.pipeline import ingest_pdf

    monkeypatch.setenv("BOXBIIBOO_ENABLE_REGION_ROUTING", "0")
    monkeypatch.setenv("BOXBIIBOO_LAYOUT_MODEL_NAME", "0")

    pdf_path = tmp_path / "sample_layout.pdf"
    _create_smoke_pdf(pdf_path)

    out = ingest_pdf(pdf_path)
    assert out["probe"]["page_count"] == 1
    assert len(out["pages"]) == 1
    assert out["blocks"]
    assert out["chunks"]
    assert "Sample Layout" in "\n".join(block.text for block in out["blocks"])


def _create_smoke_pdf(path: Path) -> None:
    import fitz

    doc = fitz.open()
    page = doc.new_page(width=595, height=842)
    page.insert_text((72, 72), "Sample Layout", fontsize=18)
    page.insert_text((72, 120), "This PDF is generated by the pipeline smoke test.", fontsize=11)
    page.insert_text((72, 150), "Metric        Value", fontsize=11)
    page.insert_text((72, 170), "Accuracy      High", fontsize=11)
    doc.save(path)
    doc.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run a manual ingest pipeline smoke check")
    parser.add_argument("pdf_path", nargs="?", default="data/sample_layout.pdf")
    args = parser.parse_args()
    main(args.pdf_path)
